# Generated by Django 5.2 on 2025-04-16 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_created_by"),
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration",
                to="events.event",
            ),
        ),
    ]
